# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
      displayName: 'Run Worksoft Executuion'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: WorksoftExecutionManager@0
  inputs:
    executiontype: 'bookmark'
    bookmarkname: 'AzureE2E_1.0'
    email: 'wsadmin@brighthousefinancial.com'
    password: $(ws_password)
    executionmanagerhostname: '10.224.11.230'
    resultattributeparameters: '1.2.3'
    resultfolder: '//DevOps//'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'